// epayco-ng/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'epayco';
}

<!--The content below is only a placeholder and can be replaced.-->
<div style="text-align:center">
  <h1>
    Welcome to {{ title }}!
  </h1>
  <img width="200" alt="Epayco Logo" src="https://multimedia.epayco.co/epayco-landing/btns/epayco-logo-fondo-oscuro.png">
</div>
<router-outlet></router-outlet>

// epayco-react/src/App.js
import React, {Fragment} from 'react';
import Succes from './components/Succes';

function App(){
    return (
      <Fragment>
        <div style={{textAlign:"center"}} >
            <h1>
                Welcome to ePayco!
            </h1>
            <img width="200" alt="Epayco Logo" src="https://multimedia.epayco.co/epayco-landing/btns/epayco-logo-fondo-oscuro.png" />
        </div>
          < Succes/>
      </Fragment>
    )
}

export default App;
