// epayco-react/src/components/Checkout.js
import React, {Component} from 'react';
import '../App.css';


export default class Checkout extends Component {
    componentDidMount () {
        const script = document.createElement("script");
    
        script.src = process.env.REACT_APP_API_URL
        script.async = true;
    
        document.body.appendChild(script);
    }
    openchekout = e =>{
        e.preventDefault();
        var handler = window.ePayco.checkout.configure({
            key: 'xxxxxxxxxxxxxxxxxxxxxxxxxx',
            test: false
        });
        let data = {
            name: "Vestido Mujer Primavera",
            description: "Vestido Mujer Primavera",
            invoice: "1234",
            currency: "cop",
            amount: '119000',
            tax_base: '100000',
            tax:  '19000',
            country: "co",
            lang: "en",
            external: "false",
            extra1: "extra1",
            extra2: "extra2",
            extra3: "extra3",
            confirmation: "http://confirmacion.php",
            response: "http://payco.co",
            name_billing: 'john doe',
            address_billing: "Carrera 19 numero 14 91",
            type_doc_billing: "cc",
            mobilephone_billing: "3050000000",
            number_doc_billing: "100000000",
            email_billing:'example@mail.co'
        }
        handler.open(data);
    }

    render(){
        return(
            <React.Fragment> 
                <div className="loader-container">
                    <div className="loading"></div>
                </div>
                <p style={{textAlign:"center"}} className="epayco-title">
                    <button id="btn_epayco" href="#" onClick={this.openchekout}>
                        <img className="btn-epayco"    src="https://multimedia.epayco.co/epayco-landing/btns/Boton-epayco-color1.png" alt="botón epayco" />
                    </button>
                </p> 
            </React.Fragment>
        )
    } 
}

// epayco-ng/src/app/components/checkout/checkout.component.ts
import { Component, OnInit, Renderer2, Inject } from '@angular/core';
import { DOCUMENT } from '@angular/common';
import { EpaycoService } from "src/app/services/epayco.service";

@Component({
  selector: 'app-checkout',
  templateUrl: './checkout.component.html',
  styleUrls: ['./checkout.component.css']
})
export class CheckoutComponent implements OnInit {

  public window:any;
  public checkoutUrl;

  constructor(
    private _renderer2: Renderer2, 
    private epaycoService: EpaycoService,
    @Inject(DOCUMENT) private _document: Document
  ) { 
    this.checkoutUrl = this.epaycoService.checkoutUrl;
  }

  ngOnInit(): void {
    let script = this._renderer2.createElement('script');
      script.src = this.checkoutUrl;
      this._renderer2.appendChild(this._document.body, script);
      this.window = window;
  }
  
  epayco(){
    let handler = this.window.ePayco.checkout.configure({ key: 'xxxxxxxxxxxxxxxxxxxxxxx', test: true });
    var data={ 
      //Parametros compra (obligatorio) 
      invoice: "1234",
      currency: "cop",
      name: "Plan de facturacion electronica",
      description: "Plan de facturacion electronica",
      tax_base: 40000,
      tax: 0,
      amount: 40000,
      country: "co",
      lang: "es",
      external: "false",
      //Onpage="false" - Standard="true" 
      //Atributos opcionales
      method:'POST',
      extra1: '',
      response: "http://localhost:4200/response",
      confirmation: "http://localhost:4200/confirmation",
    } 
    handler.open(data)
    handler.onClosed(function(response:any) {
      alert('Close ePayco Modal!')
    });
  } 

}

<p>checkout works!</p>

<div class="loader-container">
    <div class="loading"></div>
</div>
<p style="text-align: center;" class="epayco-title">
    <a id="btn_epayco" href="#">
        <img class="btn-epayco" (click)="epayco()"  src="https://multimedia.epayco.co/epayco-landing/btns/Boton-epayco-color1.png" alt="botón epayco">
    </a>
</p>    
      
<a routerLink="/response" routerLinkActive="active-link" style="display: none;">Go response</a>
