// epayco-react/src/components/checkout.js
import React, {Component} from 'react';






export default class Checkout extends Component {

    
    openchekout = e =>{
        e.preventDefault();

        var handler = window.ePayco.checkout.configure({
            key: 'xxxxxxxxxxxxxxxxxxxxxxxxxx',
            test: false
        });
    let data = {
          name: "Vestido Mujer Primavera",
          description: "Vestido Mujer Primavera",
          invoice: "1234",
          currency: "cop",
          amount: '119000',
          tax_base: '100000',
          tax:  '19000',
          country: "co",
          lang: "en",
          external: "false",
          extra1: "extra1",
          extra2: "extra2",
          extra3: "extra3",
          confirmation: "http://confirmacion.php",
          response: "http://payco.co",
          name_billing: 'john doe',
          address_billing: "Carrera 19 numero 14 91",
          type_doc_billing: "cc",
          mobilephone_billing: "3050000000",
          number_doc_billing: "100000000",
          email_billing:'example@mail.co'
          }
        handler.open(data);
    }
    render(){
       
	
        return(

                <React.Fragment>
                    
                    <input
                    type="submit"
                    placeholder="pagar"
                    onClick={this.openchekout}
                    /> 
                  
              
                    </React.Fragment>
       
        )
    } 
   
}

// epayco-ng6/src/app/components/checkout/checkout.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-checkout',
  templateUrl: './checkout.component.html',
  styleUrls: ['./checkout.component.scss']
})
export class CheckoutComponent implements OnInit {
	window: any = window;
	handler = this.window.ePayco.checkout.configure({ key: '491d6a0b6e992cf924edd8d3d088aff1', test: true });
  	constructor() { }

  ngOnInit() {
}

epayco(){
	
	
	  	var data={ 
			  //Parametros compra (obligatorio) 
		  	invoice: "1234",
		  	currency: "cop",
		  	name: "Plan de facturacion electronica",
		  	description: "Plan de facturacion electronica",
		  	tax_base: '0',
		  	tax: '0',
		  	amount: 40000,
		  	country: "co",
		  	lang: "es",
			external: "false",
			//Onpage="false" - Standard="true" 
		  	//Atributos opcionales
		  	method:'GET',
		  	extra1: '',
		  	extra2: 'ePayco',
		  	extra3: '',
		  	response: "http://localhost:4200/response",
		  	confirmation: "http://localhost:4200/confirmation",
		} 
		
		this.handler.onCloseModal = this.onCloseEpaycoModal
		this.handler.open(data)
	}
	
	onCloseEpaycoModal(){
		alert('Close ePayco Modal!!!!!!!')
	}
	
}
